version: 2
jobs:
  build:
    parallelism: 4
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          PGHOST: 127.0.0.1
          PGUSER: circleci-chicken_test
          RAILS_ENV: test
          SECRET_KEY_BASE: ce58439aef53bab181badd61f6866785d36acbae927fd75b91ce598ed180a5c1be9df625378a39b128410d0a0ca8f76bc8b72979b7e0f35d7aaa0eae9734e682
      - image: circleci/postgres:10.5-alpine
        environment:
          POSTGRES_USER: circleci-chicken_test
          POSTGRES_DB: chicken_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      - run:
          name: Copy environment
          command: cp .sample.env .env

      - run:
          name: Install Bundler
          command: gem install bundler

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      # Restore bundle cache
      - restore_cache:
          keys:
            - chicken-bundle-v2-{{ checksum "Gemfile.lock" }}
            - chicken-bundle-v2-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      # Store bundle cache
      - save_cache:
          key: chicken-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Restore Yarn cache
      - restore_cache:
          keys:
            - chicken-yarn-v2-{{ checksum "yarn.lock" }}
            - chicken-yarn-v2-

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      # Store Yarn cache
      - save_cache:
          key: chicken-yarn-v2-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database Create
          command: bin/rails db:create --trace

      - run:
          name: Database Setup
          command: bin/rails db:schema:load --trace

      # Lint factories
      - type: shell
        command: bundle exec standardrb

      # Run rspec in parallel
      - type: shell
        command: |
          bundle exec rspec --profile 10 \
            --format RspecJunitFormatter \
            --out test_results/rspec.xml \
            --format progress \
            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # Save test results for timing analysis
      - store_test_results:
          path: test_results

      # Save the tests split for replication of failures with the same seed
      - store_artifacts:
          path: test_results
          destination: test_results
